name: rocm-validation-suite
title: ROCm Validation Suite
license: MIT
version: 6.2.2
summary: A system validation and diagnostics tool for AMD GPUs
description: |
  NOTE: This is a wrapper of the official package, but it is not verified,
  affiliated with, or supported by AMD.

  The ROCm Validation Suite (RVS) is a system validation and diagnostics tool
  for monitoring, stress testing, detecting and troubleshooting issues that
  affects the functionality and performance of AMD GPU(s) operating in a
  high-performance/AI/ML computing environment. RVS is enabled using the ROCm
  software stack on a compatible software and hardware platform.

  RVS is a collection of tests, benchmarks and qualification tools each
  targeting a specific sub-system of the ROCm platform. All of the tools are
  implemented in software and share a common command line interface. Each set
  of tests are implemented in a "module" which is a library encapsulating the
  functionality specific to the tool. The CLI can specify the directory
  containing modules to use when searching for libraries to load. Each module
  may have a set of options that it defines and a configuration file that
  supports its execution.

website: https://github.com/ROCm/ROCmValidationSuite
contact: https://github.com/pedro-avalos/rocm-validation-suite-snap/issues
issues: https://github.com/pedro-avalos/rocm-validation-suite-snap/issues
source-code: https://github.com/ROCm/ROCmValidationSuite

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:

apps:
  rocm-validation-suite:
    command: opt/rocm-${SNAPCRAFT_PROJECT_VERSION}/bin/rvs
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/opt/rocm-${SNAPCRAFT_PROJECT_VERSION}/lib
      PATH: $PATH:$SNAP/opt/rocm-${SNAPCRAFT_PROJECT_VERSION}/bin
    plugs:
      - opengl
      - home
      - removable-media
      - hardware-observe
      - network-bind
      - system-observe
      - process-control
      - power-control
      - network-control
      - firewall-control
      - netlink-audit
      - netlink-connector

plugs:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404

layout:
  /usr/share/libdrm:
    bind: $SNAP/gpu-2404/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/gpu-2404/drirc.d

package-repositories:
  - type: apt
    architectures: [amd64]
    components: [main]
    suites: [noble]
    key-id: CA8BB4727A47B4D09B4EE8969386B48A1A693C5C
    url: https://repo.radeon.com/amdgpu/${SNAPCRAFT_PROJECT_VERSION}/ubuntu
  - type: apt
    architectures: [amd64]
    components: [main]
    suites: [noble]
    key-id: CA8BB4727A47B4D09B4EE8969386B48A1A693C5C
    url: https://repo.radeon.com/rocm/apt/${SNAPCRAFT_PROJECT_VERSION}
    priority: 600

parts:
  rocm-validation-suite:
    plugin: nil
    stage-packages:
      - rocm-smi-lib
      - rocrand
      - rocblas
      - hiprand
      - rocm-validation-suite
    stage:
      - -opt/amdgpu/lib/x86_64-linux-gnu/libdrm.so*
      - -opt/amdgpu/lib/x86_64-linux-gnu/libdrm_amdgpu.so*
      - -opt/rocm-${SNAPCRAFT_PROJECT_VERSION}/lib/libhiprtc.so*
      - -opt/rocm-${SNAPCRAFT_PROJECT_VERSION}/lib/liboam.so*
      - -opt/rocm-${SNAPCRAFT_PROJECT_VERSION}/lib/libncurses.so*
      - -usr/lib/x86_64-linux-gnu/libncurses.so*
      - -usr/lib/x86_64-linux-gnu/libform.so*
      - -usr/lib/x86_64-linux-gnu/libmenu.so*
      - -usr/lib/x86_64-linux-gnu/libpanel.so*
