name: rocm-validation-suite
title: ROCm Validation Suite
version: 6.2.2
summary: A system validation and diagnostics tool for AMD GPUs
description: |
  NOTE: This is a wrapper of the official package, but it is not verified,
  affiliated with, or supported by AMD.

  The ROCm Validation Suite (RVS) is a system validation and diagnostics tool
  for monitoring, stress testing, detecting and troubleshooting issues that
  affects the functionality and performance of AMD GPU(s) operating in a
  high-performance/AI/ML computing environment. RVS is enabled using the ROCm
  software stack on a compatible software and hardware platform.

  RVS is a collection of tests, benchmarks and qualification tools each
  targeting a specific sub-system of the ROCm platform. All of the tools are
  implemented in software and share a common command line interface. Each set
  of tests are implemented in a "module" which is a library encapsulating the
  functionality specific to the tool. The CLI can specify the directory
  containing modules to use when searching for libraries to load. Each module
  may have a set of options that it defines and a configuration file that
  supports its execution.

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:

apps:
  rocm-validation-suite:
    command: opt/rocm-${SNAPCRAFT_PROJECT_VERSION}/bin/rvs
    plugs:
      - opengl
      - home
      - removable-media

package-repositories:
  - type: apt
    architectures: [amd64]
    components: [main]
    suites: [noble]
    key-id: CA8BB4727A47B4D09B4EE8969386B48A1A693C5C
    url: https://repo.radeon.com/amdgpu/${SNAPCRAFT_PROJECT_VERSION}/ubuntu
  - type: apt
    architectures: [amd64]
    components: [main]
    suites: [noble]
    key-id: CA8BB4727A47B4D09B4EE8969386B48A1A693C5C
    url: https://repo.radeon.com/rocm/apt/${SNAPCRAFT_PROJECT_VERSION}
    priority: 600

parts:
  rocm-validation-suite:
    plugin: cmake
    cmake-parameters:
      - -DROCM_PATH=/opt/rocm-${SNAPCRAFT_PROJECT_VERSION}
      - -DCMAKE_INSTALL_PREFIX=/opt/rocm-${SNAPCRAFT_PROJECT_VERSION}
      - -DCPACK_PACKAGING_INSTALL_PREFIX=/opt/rocm-${SNAPCRAFT_PROJECT_VERSION}
    source: https://github.com/ROCm/ROCmValidationSuite.git
    source-type: git
    source-tag: rocm-${SNAPCRAFT_PROJECT_VERSION}
    build-snaps: [cmake]
    build-packages:
      - libpci3
      - libpci-dev
      - doxygen
      - unzip
      - libyaml-cpp-dev
      - rocm-core
      - rocm-cmake
      - hipcc
      - hip-dev
      - rocblas-dev
      - rocm-smi-lib
